# This workflow will build a .NET project and publish a nuget package
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Q3

on:
  push:
    branches: [ "Q3" ]
  pull_request:
    branches: [ "Q3" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore HelloWorld
    - name: Build
      run: dotnet build HelloWorld --no-restore
    - name: Test
      run: dotnet test HelloWorld --no-build --verbosity normal
    - name: Create the package
      run: dotnet pack -c Release ./HelloWorld
    - name: Add nuget source
      run: dotnet nuget add source --username AmyInGit --password ${{ secrets.devopstest_token }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/AmyInGit/index.json"
    - name: Publish the package to Github Packages
      run: dotnet nuget push ./HelloWorld/bin/Release/*.nupkg --api-key ${{ secrets.devopstest_token }} --source github --skip-duplicate
