# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Q3

on:
  push:
    branches: [ "Q3" ]
  pull_request:
    branches: [ "Q3" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore HelloWorld
    - name: Build
      run: dotnet build HelloWorld --no-restore
    - name: Test
      run: dotnet test HelloWorld --no-build --verbosity normal
